//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buhgalter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buhgalter()
        {
            this.Buhgalter_order = new HashSet<Buhgalter_order>();
            this.Buhgalter_company = new HashSet<Buhgalter_company>();
        }
    
        public int Buhgalter_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> dateprihod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buhgalter_order> Buhgalter_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buhgalter_company> Buhgalter_company { get; set; }
    }
}
