//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laborant_Data_Orders
    {
        public int Laborant_Data_Orders_id { get; set; }
        public Nullable<int> Laborant_Data_id { get; set; }
        public Nullable<int> Orders_id { get; set; }
    
        public virtual Laborant_Data Laborant_Data { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
