//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Met_Lab_N20Entities : DbContext
    {
        public Met_Lab_N20Entities()
            : base("name=Met_Lab_N20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<analizator_data> analizator_data { get; set; }
        public virtual DbSet<Buhgalter> Buhgalter { get; set; }
        public virtual DbSet<Buhgalter_company> Buhgalter_company { get; set; }
        public virtual DbSet<Buhgalter_order> Buhgalter_order { get; set; }
        public virtual DbSet<Lab_Serveces> Lab_Serveces { get; set; }
        public virtual DbSet<Laborant_Data> Laborant_Data { get; set; }
        public virtual DbSet<Laborant_Data_Orders> Laborant_Data_Orders { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pat_Serv> Pat_Serv { get; set; }
        public virtual DbSet<Patient_Data> Patient_Data { get; set; }
        public virtual DbSet<SaveCompanyData> SaveCompanyData { get; set; }
        public virtual DbSet<Serv_order> Serv_order { get; set; }
        public virtual DbSet<Servicesout> Servicesout { get; set; }
    }
}
