//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Buhgalter_company = new HashSet<Buhgalter_company>();
            this.Buhgalter_order = new HashSet<Buhgalter_order>();
            this.Laborant_Data_Orders = new HashSet<Laborant_Data_Orders>();
            this.Serv_order = new HashSet<Serv_order>();
        }
    
        public int Orders_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Patient_Data_id { get; set; }
        public string status_order { get; set; }
        public string status_serv { get; set; }
        public Nullable<int> period { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buhgalter_company> Buhgalter_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buhgalter_order> Buhgalter_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laborant_Data_Orders> Laborant_Data_Orders { get; set; }
        public virtual Patient_Data Patient_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serv_order> Serv_order { get; set; }
    }
}
