//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient_Data()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Patient_Data_id { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public string social_sec_number { get; set; }
        public string ein { get; set; }
        public string social_type { get; set; }
        public string telefon { get; set; }
        public Nullable<int> series { get; set; }
        public Nullable<int> number { get; set; }
        public string Birthday { get; set; }
        public string country { get; set; }
        public string insurance_name { get; set; }
        public string insurance_address { get; set; }
        public string insurance_inn { get; set; }
        public string ipadress { get; set; }
        public string insurance_pc { get; set; }
        public string insurance_bik { get; set; }
        public string ua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
