//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_LAb_N20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicesout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicesout()
        {
            this.Serv_order = new HashSet<Serv_order>();
        }
    
        public int Servicesout_id { get; set; }
        public Nullable<int> Lab_Serveces_id { get; set; }
        public Nullable<int> Laborant_Data_id { get; set; }
        public Nullable<int> analizator_data_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual analizator_data analizator_data { get; set; }
        public virtual Lab_Serveces Lab_Serveces { get; set; }
        public virtual Laborant_Data Laborant_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serv_order> Serv_order { get; set; }
    }
}
